Added quotation marks to TargetPath as a post build event in visual studio. Directories with a space caused a problem.
Changed the generation of Proxy_class function pointers, the following gave an error in visual studio
struct foo
{
	//foo(){}
};

struct bar
{
	foo baz(){return foo();}
};
int main()
{
	static foo(bar::*func_ptr)() = &bar::baz;
}
/*
error C2440: 'initializing' : cannot convert from 'foo (__thiscall bar::* )(void)' to 'foo (__thiscall bar::* )(void)'
Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast

Uncomment foo constructor to compile
or 
Remove static from pointer instance
*/